#This app is used for the PhD research in the University of Malaga 
# We will build an Ontology for deployment on Kubernetes 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ontology-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 730785221004.dkr.ecr.us-east-1.amazonaws.com/ontology:v1
        ports:
        - containerPort: 80
        imagePullPolicy: Always  
---
apiVersion: v1
kind: Service
metadata:
  name: ontology-service
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
     #The loadbalancer listening on this port
      port: 80
      targetPort: 80